### ISSUE TITLE
Export only a VM disk

### ISSUE THREAD

**Issue by wefixit-AT** [wefixit-AT/oVirtBackup#11]
Today I had some troubles (found a bug in oVirt). Then I came to the idea to export only a selected disk to another location to split system and data files better. With the current solution all disks (system and data) will be copied, which could take a really long time for big data disks. The data disk should anyway be backed up with a solution which supports incremental or differential backups.

**Comment by seryeb** [comment]
Hi! This is a very interesting idea!

@alvarogomez93 and me have adapted the backup.py script for our interests: if only the system disk is bootable, we can create a snapshot with the bootable disk, and not the "data" disk:

```
109a110,122
>             # Get the Bootable Disk
>             disks = vm.disks
> 
>             discoBootable = None
>             for discoi in disks.list():
>                 if discoi.bootable == True:
>                     discoBootable = discoi
>                     break
> 
>             discoSnap= params.Disks()
>             discoSnap.add_disk(discoBootable)
> 
> 
112c125
<         
---
> 
117a131
> 
123c137
<                     vm.snapshots.add(params.Snapshot(description=config.get_snapshot_description(), vm=vm))
---
>                     vm.snapshots.add(params.Snapshot(description=config.get_snapshot_description(), disks=discoSnap, vm=vm))
147c161
<         
---
> 
193a208
> 
```

**Comment by wefixit-AT** [comment]
Can you create a pull request

**Comment by mkhoroshev** [comment]
**seryeb**, thank you! Working like a charm! It will be more flexible if implement a config option like a boot_disk_only: yes
