### ISSUE TITLE
vm_middle= deletes original VM

### ISSUE THREAD

**Issue by Nail87** [wefixit-AT/oVirtBackup#15]
Let me lead with GREAT script and thanks for sharing! I have found a way that a idiot like myself can use the script to delete all my original VMs. If you leave vm_middle blank it will try to delete the originals. I was thinking that leaving it blank would make the names shorter... thus less errors in the future? My mistake...

To help make it a little more dummy proof maybe you can throw a if statement in there to look for a blank variable and quit safely? Thanks again for all the hard work you have done on this.

**Comment by wefixit-AT** [comment]
Sorry to hear that, you make a good point. I will add this check ASAP

**Comment by wefixit-AT** [comment]
A change was made to the code to detect empty vm_middle to prevent this. Can you please check it to close this issue.

**Comment by Nail87** [comment]
Thank you!
