### ISSUE TITLE
Cannot add VM. Snapshot is currently being created for VM ...

### ISSUE THREAD

**Issue by wefixit-AT** [wefixit-AT/oVirtBackup#17]
Sometimes I get this problem on one of my machines. 

I'm working currently on this. The SDK returns that there is no running job but I still get an RequestError Exception from the SDK :-(

**Comment by wefixit-AT** [comment]
Added a short delay after the snapshot operation

**Comment by mykaul** [comment]
@wefixit-AT - did you report this SDK issue to oVirt?
