### ISSUE TITLE
Feature wish: Define config parameters on the commandline or complete config via stdin

### ISSUE THREAD

**Issue by fthommen** [wefixit-AT/oVirtBackup#19]
It would be nice, if
1. configuration parameters could be defined on the commandline instead of in the configuration file and if commandline parameters would overwrite configfile settings
2. the configuration file could be given via stdin

this would come in very handy for automation and dynamic configuration settings.  E.g. in setups where many VMs have to be backed up in regular intervals - but never all together -, it is not practicable to create a config file for each single VM.  90% of the configuration would be redundant and would have to be changed in all configuration files if e.g. the name of the storage domain changes. 

@ 1.: 
this (by itself incomplete) configuration file:

```
[config]
# vm_names: define them on the commandline
vm_middle=_BACKUP
snapshot_description=Snapshot for backup script
server=https://my.ovirt.server/ovirt-engine/api
username=my_username
password=my_admin_password
export_domain=my_storage_domain
timeout=5
cluster_name=my_clustername
backup_keep_count=3
dry_run=False
vm_name_max_length=32
storage_domain=my_storage_domain
storage_space_threshold=0.1
use_short_suffix=false
```

could be run with in dry mode with:
`backup.py -d -c ./global-backupsettings.conf --vm_names=vm1,vm2,vm3 --dry_run=true`

(writing this I notice, that the `vm_names` directive has a different syntax from all other settings.  Wouldn't it be nice to have the same syntax everywhere?  I.e. `vm_name = vm1, vm2, vm3` instead of `vm_names: ["vm1", "vm2", "vm3"]`?)

@ 2.
As alternative (or additionally), the configuration file could be given via stdin.  E.g. using above example:

```
(echo 'vm_names: ["vm1", "vm2", "vm3"]'; \
 cat  ./global-backupsettings.conf;      \
 echo "dry_run=True") | ./backup.py -d
```

Not as nice as the commandline options but still usable for automation and dynamic configurations :-)

Cheers
Frank

**Comment by lukas-bednar** [comment]
Try following
```sh
(echo 'vm_names = ["vm1", "vm2", "vm3"]'; \
 cat  ./global-backupsettings.conf;      \
 echo "dry_run=True") | ./backup.py -d -c -
```
or this following command
```sh
./backup.py -d --dry-run --vm-names '["vm1", "vm2", "vm3"]' -c ./global-backupsettings.conf
```
with #31 PR.
