### ISSUE TITLE
unsupported operand type(s) for +=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by linuskohl** [wefixit-AT/oVirtBackup#20]
I got the error "unsupported operand type(s) for +=: 'int' and 'NoneType'" and temporarily fixed it 
with vmtools.py
```
<             vm_size += disk.size
---
>             if disk.size is not None:
>                 vm_size += disk.size
```
Unfortunately I could not dig deeper into the error and do not know when it happens.

**Comment by wefixit-AT** [comment]
Thanks for sharing, added to the code
