### ISSUE TITLE
Bug: The scripts refuse to execute because a machine not included in the config file

### ISSUE THREAD

**Issue by Deicidium** [wefixit-AT/oVirtBackup#22]
oVirt version: oVirt 3.6.7.5-1.el7.centos
OS Version: RHEL - 7 - 2.1511.el7.centos.2.10
Kernel Version: 3.10.0 - 327.28.2.el7.x86_64
KVM Version: 2.3.0 - 31.el7_2.10.1
LIBVIRT Version: libvirt-1.2.17-13.el7_2.5
VDSM Version: vdsm-4.17.32-1.el7
SPICE Version: 0.12.4 - 15.el7_2.1
GlusterFS Version: glusterfs-3.8.1-1.el7
CEPH Version: librbd1-0.80.7-3.el7

Python packages:

python-pip-7.1.0-1.el7.noarch
python-kitchen-1.1.1-5.el7.noarch
ovirt-engine-sdk-python-3.6.7.0-1.el7.centos.noarch
libxml2-python-2.9.1-6.el7_2.3.x86_64
newt-python-0.52.15-4.el7.x86_64
policycoreutils-python-2.2.5-20.el7.x86_64
python-urwid-1.1.1-3.el7.x86_64
python-setproctitle-1.1.6-5.el7.x86_64
python-pyudev-0.15-7.el7_2.1.noarch
python-perf-3.10.0-327.28.2.el7.x86_64
python-devel-2.7.5-38.el7_2.x86_64
python-javapackages-3.4.1-11.el7.noarch
python-slip-0.4.0-2.el7.noarch
python-markdown-2.4.1-1.el7.centos.noarch
python-urlgrabber-3.10-7.el7.noarch
rpm-python-4.11.3-17.el7.x86_64
python-ethtool-0.8-5.el7.x86_64
python-rtslib-2.1.fb57-3.el7.noarch
python-psycopg2-2.5.1-3.el7.x86_64
dbus-python-1.1.1-9.el7.x86_64
libselinux-python-2.2.2-6.el7.x86_64
python2-ecdsa-0.13-4.el7.noarch
python-IPy-0.75-6.el7.noarch
python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64
python-pycurl-7.19.0-17.el7.x86_64
python-ply-3.4-10.el7.noarch
python2-paramiko-1.16.1-1.el7.noarch
python-setuptools-0.9.8-4.el7.noarch
python-nose-1.3.0-3.el7.noarch
python-cheetah-2.4.4-5.el7.centos.x86_64
python-six-1.9.0-2.el7.noarch
python-kmod-0.9-4.el7.x86_64
python-configshell-1.1.fb18-1.el7.noarch
python-chardet-2.2.1-1.el7_1.noarch
python-libs-2.7.5-38.el7_2.x86_64
audit-libs-python-2.4.1-5.el7.x86_64
python-decorator-3.4.0-3.el7.noarch
python-iniparse-0.4-9.el7.noarch
libsemanage-python-2.1.10-18.el7.x86_64
python2-crypto-2.6.1-9.el7.x86_64
python-daemon-1.6-4.el7.noarch
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-pygments-1.4-9.el7.noarch
lvm2-python-libs-2.02.130-5.el7_2.5.x86_64
python-2.7.5-38.el7_2.x86_64
python-slip-dbus-0.4.0-2.el7.noarch
python-lockfile-0.9.1-4.el7.centos.noarch
python-backports-1.0-8.el7.x86_64
python-dateutil-1.5-7.el7.noarch
systemd-python-219-19.el7_2.12.x86_64
python-lxml-3.2.1-4.el7.x86_64
python-configobj-4.7.2-7.el7.noarch
cracklib-python-2.9.0-11.el7.x86_64
python-websockify-0.6.0-2.el7.noarch

Description: In the Config File only exists the Ansible_Prod VM but the backup's log says :

Aug 23 07:57:52: Start backup for: Ansible_Prod
Aug 23 07:57:53: !!! Can't delete cloned VM (PerseoVoto_Prod)
Aug 23 07:57:53: !!! Got unexpected exception: 'ascii' codec can't encode character u'\xf1' in position 17: ordinal not in range(128)

Backup doesn't executate.

Thanks in regard

**Comment by Trefex** [comment]
Are you sure the VM is not called Ansible-Prod? I thought oVirt would not allow special characters such as _?

**Comment by wefixit-AT** [comment]
Since this issue is now over two years old this will be closed
