### ISSUE TITLE
Backup for Storage

### ISSUE THREAD

**Issue by jeaneduardo** [wefixit-AT/oVirtBackup#24]
Hello, first congratulates him for the application.
The application exports the backup to a NFS, in my case I have a storage for backup, it is possible to export the snapashots to another volume Fibre Channel

Regards,
Jean Eduardo
Brazil

**Comment by jprates88** [comment]
Hello Jean,

Backup you could make the VMs? for me shows the error message:

2016-10-25 15:32:34,185 ERROR [org.ovirt.engine.api.restapi.util.LinkHelper] (default task-46) [] Can't find relative path for class "org.ovirt.engine.api.resource.VmDisksResource", will return null

**Comment by Trefex** [comment]
@jeaneduardo i guess not, you can only export to an EXPORT domain which by oVirt definition can only be NFS.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
