### ISSUE TITLE
Failed backup VM

### ISSUE THREAD

**Issue by jprates88** [wefixit-AT/oVirtBackup#25]
Failed backup VM using API.

Message Error:

2016-10-25 15:32:34,185 ERROR [org.ovirt.engine.api.restapi.util.LinkHelper](default task-46) [] Can't find relative path for class "org.ovirt.engine.api.resource.VmDisksResource", will return null

**Comment by jprates88** [comment]
Version Pytons;

python-ovirt-engine-sdk4-4.0.1-1.el7ev.x86_64
virt-engine-restapi-4.0.3-0.1.el7ev.noarch
ovirt-engine-4.0.3-0.1.el7ev.noarch
ovirt-engine-sdk-python-3.6.9.1-1.el7ev.noarch

**Comment by wefixit-AT** [comment]
You have installed sdk 4 and sdk 3 which will not work. Please install only sdk 3, for more informations about sdk 4 take a look alt #21

**Comment by vinaobraga** [comment]
Hello, we can not remove the sdk 4 version because it is required.

**Comment by wefixit-AT** [comment]
see #26

**Comment by jprates88** [comment]
Hello.

It is working now!!!!! :)

There is a flag on config.cfg file set to True by default:

If set to "True" no creation, deletion and other operations will be executed
dry_run=True

I changed it to False and the backup was made with success:

[root@cpsvrhevmp01 oVirtBackup-master]# ./backup.py -c config_example.cfg
Nov 03 10:43:48: Start backup for: CPSVZABBIXP01
Nov 03 10:43:49: Snapshot creation started ...
Nov 03 10:44:01: Snapshot created
Nov 03 10:44:11: Clone into VM started ...
Nov 03 10:46:23: Cloning finished
Nov 03 10:46:25: Snapshot deletion started ...
Nov 03 10:48:47: Snapshots deleted
Nov 03 10:48:49: Export started ...
Nov 03 10:52:19: Exporting finished
Nov 03 10:52:19: Delete cloned VM started ...
Nov 03 10:52:22: Cloned VM deleted
Nov 03 10:52:22: Duration: 8:35 minutes
Nov 03 10:52:22: VM exported as CPSVZABBIXP01_BACKUP_20161103_104348
Nov 03 10:52:22: Backup done for: CPSVZABBIXP01
Nov 03 10:52:22: All backups done
[root@cpsvrhevmp01 oVirtBackup-master]#

So, I think it is necessary to change it on the download zip package to False.

Tks.
