### ISSUE TITLE
Command Line Switch to Backup All VMs Not Working With oVirt 4.0.5

### ISSUE THREAD

**Issue by dbec** [wefixit-AT/oVirtBackup#27]
When I use the "-a" switch to backup all VMs, as follows...
python /home/backup/oVirtBackup/backup.py -c config.cfg -a -d
...I get this error:
Nov 18 14:35:50: Unexpected error getting list of vms: [Errno 18] Invalid cross-device link
The backup continues to run for all the VMs in config.cfg, but does not backup all VMs, as expected with this switch.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
