### ISSUE TITLE
Does it work with oVirt 4.1 and 3.6 SDK?

### ISSUE THREAD

**Issue by Trefex** [wefixit-AT/oVirtBackup#29]
Hi,

Not really an issue, but rather a question.

Does it work with oVirt 4.1 and 3.6 SDK?

Thanks,
T

**Comment by lukas-bednar** [comment]
I can confirm that it works for me.

ovirt-engine-sdk-python-3.6.9.2-0.1.20170209.gite99bbd1.fc25.noarch

**Comment by Trefex** [comment]
@lukas-bednar hi thanks, but have you faced this issue?

http://lists.ovirt.org/pipermail/users/2017-March/080338.html

It seems in 4.1, the default is now to pause the VMs which would not be nice.

**Comment by Aleksey-Maksimov** [comment]
I have the same problem. VM turn into a pause during backup

**Comment by Trefex** [comment]
@lukas-bednar could you integrate this patch from the mailing list into the code? I think the default changed so that oVirtBackup now uses "wrong" default.

What do you think?

**Comment by wefixit-AT** [comment]
Can you please create a pull request

**Comment by lukas-bednar** [comment]
@Trefex yes I was able to reproduce that.
Unfortunately there is no option to change this value in system via engine-config, so changing in backup script inevitable.
