### ISSUE TITLE
There are many calls of vms.list in the script

### ISSUE THREAD

**Issue by lukas-bednar** [wefixit-AT/oVirtBackup#32]
It would be nice to aim every query to search for specific vm(s) instead of pooling all the time all set of vms.
In addition there is used `max=400` keyword which potentially truncate results which we could be interested in.

I suggest at least these two improvements:

1) When you look for cloned vms, you can use vms.list(query="name=original_vm*")

2) when you search for specific vm, just use vms.get("vm_name"), for example when you wait until it is removed. Or for verification whether vm exists.

**Comment by wefixit-AT** [comment]
Can you please check if this is resolved by the changes from KKoukiou

**Comment by lukas-bednar** [comment]
@wefixit-AT yes she covered that :+1:
@KKoukiou thanks!

**Comment by mykaul** [comment]
Looks great!
One small optimization: when iterating over the VMs, I'm not sure why we need to wait for each VM to be deleted. Just delete all the relevant ones, then iterate over all of them again and ensure they are all deleted.
