### ISSUE TITLE
multiple VMs don't work

### ISSUE THREAD

**Issue by paf1** [wefixit-AT/oVirtBackup#4]
I've got issue with  backup more than one VM in config file 

================================================================
$./backup.py -c config-TEST.cfg  -d
Jan 21 17:34:17: Start backup for: test2
Jan 21 17:34:39: Snapshot creation started ...
Jan 21 17:34:40: Snapshot operation(creation) in progress ...
Jan 21 17:34:46: Snapshot operation(creation) in progress ...
Jan 21 17:34:51: Snapshot operation(creation) in progress ...
Jan 21 17:34:57: Snapshot created
Jan 21 17:34:58: Clone into VM started ...
Jan 21 17:35:00: Cloning in progress ...
Jan 21 17:35:05: Cloning in progress ...
Jan 21 17:35:22: Cloning in progress ...
Jan 21 17:35:27: Cloning finished
Jan 21 17:35:28: Found snapshots(1):
Jan 21 17:35:28: Snapshots description: Snapshot for backup script, Created on: 2016-01-21 17:34:39.696000+01:00
Jan 21 17:35:28: Snapshot deletion started ...
Jan 21 17:35:29: Snapshot operation(deletion) in progress ...
Jan 21 17:37:22: Snapshot operation(deletion) in progress ...
Jan 21 17:37:27: Snapshots deleted
Jan 21 17:37:29: Export started ...
Jan 21 17:37:31: Exporting in progress ...
Jan 21 17:37:59: Exporting in progress ...
Jan 21 17:38:04: Exporting finished
Jan 21 17:38:26: Delete cloned VM started ...
Jan 21 17:38:48: Cloned VM deleted
Jan 21 17:38:48: Duration: 4:32 minutes
Jan 21 17:38:48: VM exported as test2_BACKUP_1453394056
Jan 21 17:38:48: Backup done for: test2
Jan 21 17:38:48: All backups done
Jan 21 17:38:48: Backup failured for:
Jan 21 17:38:48:   test1

================================================================

$ cat config-TEST.cfg
[config]
vm_names: ["test2","test1"]
vm_middle=_BACKUP
snapshot_description=Snapshot for backup script
server=https://ovirt
username=admin@internal
password=
export_domain=BACKUP-export
timeout=5
cluster_name=KVM-prod
backup_keep_count=21
dry_run=False

================================================================

running on 
GUI - oVirt Engine Version: 3.5.2.1-1.el7.centos
ovirt-engine-sdk-python-3.5.5.0-1.el7.centos.noarch
python-2.7.5-18.el7_1.1.x86_64

regs. Pavel

**Comment by wefixit-AT** [comment]
Can you test the tool only with the VM "test1" and report if it fails.
Which version of the SDK have you installed?
How much memory has the oVirt Host and does it use swap? I had troubles with a machine which has low free memory and I realized that the oVirt SDK use a lot of memory during backup. This increased for version 3.6.

**Comment by paf1** [comment]
I test it with both  VMs in single configuration ( no problems ) or in 
oposit list ( same problem with second VM )

ovirt-engine-sdk-python-*3.5.5.0-1*.el7.centos.noarch
5GB mem
4 CPU

swapon -s
Filename                            Type            Size Used    Priority
/dev/sda1                           partition       2097148 *672480*  -1


Pa.

**Comment by wefixit-AT** [comment]
Can you check the ovirt log, maybe there are some hints.
In the meantime I create two test VM's to try to reproduce. I hope this can also be reproduced with empty VM's

**Comment by paf1** [comment]
python-2.7.5-18.el7_1.1.x86_64
ovirt-engine-sdk-python-*3.5.5.0-1*.el7.centos.noarch
Will check other logs ...

**Comment by paf1** [comment]
there are no records in any logs from backup script

**Comment by wefixit-AT** [comment]
There are many entries which came from the tool which uses the SDK to the engine in the engine.log

for example: *org.ovirt.engine.core.bll.CreateAllSnapshotsFromVmCommand* 
and many many more.

But i try to reproduce it and give you a feedback in some minutes. I never run the script directly from the host normally from my backup server, which is a VM running on that host to keep the host as minimalist as possible.

**Comment by wefixit-AT** [comment]
Thanks for reporting this problem, can you please checkout and test it on your side.
It was a really simple glitch, maybe because I switched between to much languages :-D
But these are the advantage for publish it as OpenSource so others can use it and help to improve it.

**Comment by paf1** [comment]
FIXED ! - now, multiple VMS are backuped correctly .

great thanks. Pa.
