### ISSUE TITLE
Snapshot not deleted at error

### ISSUE THREAD

**Issue by pemca** [wefixit-AT/oVirtBackup#42]
Hi,
If an error occours for some reason, and snapshot already has beed created for a VM, it is not deleted before going to the next VM.
br,
Peter C

**Comment by Aleksey-Maksimov** [comment]
+1

**Comment by jaganz** [comment]
+1

**Comment by stolp** [comment]
+1

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
