### ISSUE TITLE
How to use --vm-names parameter in the help?

### ISSUE THREAD

**Issue by arm2arm** [wefixit-AT/oVirtBackup#44]
thanks for the cool project!
will be nice to provide some examples in the help page.
I just accidentally found the solution:)

--vm-names='["render01.vm","render02.vm"]'

**Comment by githubjbw** [comment]
I ran into the same thing, trying to figure out how to pass the VM names via the command line. Thanks, your post helped as that is the one combination I had not yet tried.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
