### ISSUE TITLE
--tag="" Issue

### ISSUE THREAD

**Issue by githubjbw** [wefixit-AT/oVirtBackup#45]
`    if opts.vm_tag:
        vms=api.vms.list(max=400, query="tag="+opts.vm_tag)
        config.set_vm_names([vm.name for vm in vms])`

On my box, the max=400 is causing issues with the api.vms.list call. If I remove it, no issues. I'm not sure the reason for max= but on my box it seems to cause issues if it's there.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
