### ISSUE TITLE
Directly backup snapshots without exporting to VM (oVirt API)

### ISSUE THREAD

**Issue by mikelupe** [wefixit-AT/oVirtBackup#47]
Hello - could this be the point where it would be possible?

https://bugzilla.redhat.com/show_bug.cgi?id=1405805
https://ovirt.org/develop/release-management/features/storage/backup-restore-disk-snapshots/

https://ovirt.org/release/4.2.0/#ovirt-engine-sdk-4-python
The release notes for 4.2.0 point to those URLs in that chapter.

Regards

**Comment by pujan14** [comment]
+1

**Comment by tiny-rick1** [comment]
+1

**Comment by keulator** [comment]
+1 from here

**Comment by rightkick** [comment]
+1

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
