### ISSUE TITLE
Disk selection for snapshot

### ISSUE THREAD

**Issue by tiny-rick1** [wefixit-AT/oVirtBackup#48]
It would be nice to select disk for snapshot to be exported ( if there ar multiple disk in VM).
I have couple of VMs with large second disk for data witch i am backing up with another solution, and just want to backup the os disk for easier recovery.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
