### ISSUE TITLE
Make the clone disks into another storage domain possible?

### ISSUE THREAD

**Issue by gcecchi** [wefixit-AT/oVirtBackup#49]
Hello,
I see that I can only select cluster for destination of th eclone of the snapshot.
In my case I have only one cluster composed by two hosts, bu I have a dedicated storage domain where I would like to put the cloned disks, is it possible?
At the moment I have not enough space on source storage domain to contain the cloned disks...
Thanks,
Gianluca

**Comment by germanovm** [comment]
Would need to at the following for each disk:

        disk_attachments=[
            types.DiskAttachment(
                disk=types.Disk(
                    id='56aa4c25-4430-462d-9d9b-5683ee257711',
                    storage_domains=[
                        types.StorageDomain(
                            id='995af15c-a14e-461a-80b8-742c3bf81ff2'
                        ),
                    ],
                ),
            ),
        ],

Here: https://github.com/wefixit-AT/oVirtBackup/blob/master/backup.py#L326

**Comment by germanovm** [comment]
In fact it needs to be image_id instead of id inside the Disk element.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
