### ISSUE TITLE
Unicode Error thrown when backing up second machine in list

### ISSUE THREAD

**Issue by mikelupe** [wefixit-AT/oVirtBackup#50]
Hello
since Feb 15th '18 the second of my VMs in the backup list throws an error every time oVirtBackup tries to back it up:
"!!! Got unexpected exception: 'ascii' codec can't encode character u'\xfc' in position 25: ordinal not in range(128)"

Some research led me to this:
https://docs.python.org/2.7/howto/unicode.html#the-unicode-type

I think this error was only thrown after I upgraded oVirt to 4.2.1, as it started shortly after 4.2.1 was released on Feb 12th '18. And btw, bacchus isn't able to backup the same VM either.

Maybe this happens because the oVirt API received some changes? See: https://github.com/wefixit-AT/oVirtBackup/issues/47

Thanks for a hint.

EDIT: I executed all of the steps manually over the oVirt Webui (snapshot, clone, export and delete all items) for the same VM and this works without any problems.

**Comment by valerymamontov** [comment]
Decision: delete all snapshots with character u'\xfc' manually. Or rename all.

For example: If the name of snapshot contains Cyrillic symbols the script returns an exception.
Others VM in list do not cloned.
An exception occurs when the script executes line № 305:
```
            # Delete old backup snapshots
            VMTools.delete_snapshots(vm, config, vm_from_list)
```

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
