### ISSUE TITLE
Backup fails completely if VM missing

### ISSUE THREAD

**Issue by ghost** [wefixit-AT/oVirtBackup#52]
I recently deleted a VM but neglected to remove it from the list in config.cfg. This resulted in oVirtBackup bombing out with an error message in the log and no VM backups taken. This is highly undesirable behaviour and I believe a more appropriate response would be to log the error but continue to backup the remainder of the listed VMs. Please consider making the change.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
