### ISSUE TITLE
API version 4 required (v3 support dropped with oVirt engine 4.3)

### ISSUE THREAD

**Issue by jofleck** [wefixit-AT/oVirtBackup#56]
Hi, 
yesterday oVirt 4.3 was released. We checked the release notes and noticed that they dropped the v3 API Support. Did someone already played around with the (not well documented) v4 SDK to keep this nice script working with the v4.3 engine?

**Comment by wefixit-AT** [comment]
Thanks for the information I'm working on API v4 support since v4 was released. If I find some time I try to finish the work.
Anybody who is interested in porting the Tool to API v4 ware welcome

**Comment by stolp** [comment]
For the record: oVirtBackup still works with oVirt 4.3 (I am using it). v3 API support will be gone with oVirt 4.4.

**Comment by Senturion2006** [comment]
./backup.py -h
Traceback (most recent call last):
  File "./backup.py", line 4, in <module>
    import ovirtsdk.api
ImportError: No module named ovirtsdk.api

python-ovirt-engine-sdk4 installed

oVirt 4.3.7

**Comment by wefixit-AT** [comment]
> For the record: oVirtBackup still works with oVirt 4.3 (I am using it). v3 API support will be gone with oVirt 4.4.

This will be a problem, please open a new issue for this because Senturion2006  found a solution for the given issue.
