### ISSUE TITLE
Cyrillic symbol in name of snapshot

### ISSUE THREAD

**Issue by valerymamontov** [wefixit-AT/oVirtBackup#59]
Warning!
If the name of snapshot contains Cyrillic symbols the script returns an exception.
Others VM in list do not cloned.
An exception occurs when the script executes line № 305:
```
            # Delete old backup snapshots
            VMTools.delete_snapshots(vm, config, vm_from_list)
```
Log:
2019-11-22 08:52:24,276: Start backup for: BARS
2019-11-22 08:52:24,863: !!! Got unexpected exception: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

Decision: delete snapshot with Cirillic symbol manually. Or rename.

from russian:
Если в виртуальной машине есть снапшот, который содержит кириллицу, то скрипт вызовет исключение. Виртуальная машина склонирована не будет. 
Все остальные ВМ, указанные в списке, не склонируются.

Решение: удалите такой снапшот или переименуйте его.

**Comment by wefixit-AT** [comment]
Thank you I will put this in the README
