### ISSUE TITLE
too long filename

### ISSUE THREAD

**Issue by paf1** [wefixit-AT/oVirtBackup#6]
Hello,
next issue with backup script

./backup.py -c config-TUTYSERVIS.cfg
Jan 21 20:28:30: Start backup for: TUTYSERVIS
Jan 21 20:28:53: Snapshot creation started ...
Jan 21 20:29:19: Snapshot created
Jan 21 20:29:21: Clone into VM started ...
Jan 21 20:29:22: !!! Got a RequestError:
status: 400
reason: Bad Request
detail: Cannot add VM. The given name is too long.
Jan 21 20:29:22: All backups done
Jan 21 20:29:22: Backup failured for:
Jan 21 20:29:22:   TUTYSERVIS
Jan 21 20:29:22: Some errors occured during the backup, please check the log file

We have two posilbilities to solve this 
1) skip middle part of generated new name ( not recommended - will solve a few names only, we have very long onces up to 16 ( sixteen ) characters  )
2) make shorter time identification (or skip it ) in suffix part of new name 

=========================================================================
running on
GUI - oVirt Engine Version: 3.5.2.1-1.el7.centos
ovirt-engine-sdk-python-3.5.5.0-1.el7.centos.noarch
python-2.7.5-18.el7_1.1.x86_64

regs. Pavel

**Comment by wefixit-AT** [comment]
Thanks, First let's figure out the maximal allowed name size by oVirt.
Maybe you have some time and can get these information's?

**Comment by paf1** [comment]
let me know how, pls.

**Comment by paf1** [comment]
MaxVmNameLengthNonWindows -	Max VM name length for non-Windows OS -	Integer -	Maximum name length for a non-Windows VM   ???

**Comment by wefixit-AT** [comment]
You can use your preferred search engine + read through the oVirt Documentation and oVirt SDK Documentation. Guessing is also a way but very imprecise because someone have coded the name limit anywhere. If its not documented anywhere It must be anywhere in the code, its also OpenSource.

**Comment by paf1** [comment]
UPDATED
MaxVmNameLengthNonWindows -	Max VM name length for non-Windows OS = 64
MaxVmNameLengthWindows - Max VM name length in Windows  = 16

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.2/html/Administration_Guide/Red_Hat_Enterprise_Virtualization_Manager_configuration_options_explanations_limitations_and_best_practices.html

**Comment by wefixit-AT** [comment]
Hopefully its possible to get the type with the oVirt SDK.
I will code this tomorrow.

**Comment by paf1** [comment]
If you dive deeply in code, let me know if exists posibility to set MaxVmNameLengthWindows longer then 16 in any cfg file without impacting  current oVirt DB structure, pls.

**Comment by paf1** [comment]
SOLUTION
[root@ovirt backup]# engine-config --get=MaxVmNameLengthWindows --cver=general
15
[root@ovirt backup]# engine-config --set MaxVmNameLengthWindows=36 --cver=general
[root@ovirt backup]# engine-config --get=MaxVmNameLengthWindows --cver=general
36
===========================================================================

Well , this is fixed now, but would you generate human number format suffix ( 1501212245 eg:?  ), pls.,
regs. Pavel

**Comment by wefixit-AT** [comment]
I added a separate config for this, your solution is good but its a workaround and didn't catch or solve the problem ;-). Besides its a little bit strange that for windows vm's only 15 characters are allowed.

For the suffix i will create a separate issue, for documentation purpose.

**Comment by GusevVictor** [comment]
Thank a lot for your solutions! It looks like OK!
