### ISSUE TITLE
Error in VM nameresolution on delete cloned-vm

### ISSUE THREAD

**Issue by MEy3** [wefixit-AT/oVirtBackup#60]
There is a error on resolving the name of the cloned vm to get deleted.

If you name a vm "Test" and the second "Test2" the nameresolution might fail if you try to backup "Test". 
This is because the "*" on line 84 in vmtools.py:
vm_search_regexp = ("name=%s%s*" % (vm_name, config.get_vm_middle()))
and result in the following log:

2020-01-26 00:06:15,490: Start backup for: Test
2020-01-26 00:06:15,541: Delete cloned VM (Test2) started ...
2020-01-26 00:06:16,956: !!! Can't delete cloned VM (Test2)

I've edited the line to:
vm_search_regexp = ("name=%s%s__*" % (vm_name, config.get_vm_middle()))
and now running a test.

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

**Comment by stolp** [comment]
I think this issue should not be closed blindly.

AFAICS the code part in question has not been changed and the issue raised seems reasonable to me.

**Comment by wefixit-AT** [comment]
Thanks for the quick response, I reopen the issue.
Have you tested the issue with the latest release? And please tell us more about your environment.

**Comment by stolp** [comment]
I am first going to test the api4 changes against our oVirt 4.3 installation anyway.

So I can include this corner case as well.

I will let you know of the results here.

Thanks for still caring for this project!

**Comment by MEy3** [comment]
i've tested my changes from my initial post now for almost one year and it fixed the behavior and working without any issues on oVirt 4.3.

**Comment by wefixit-AT** [comment]
@MEy3 Thanks for the response

@stolp If you still have problems please open a new issue

**Comment by MEy3** [comment]
So you added my changes to your code? The Issue is in your lastest public version of this project still present until you changed your code like i did and written in the initial post of this issue.

**Comment by stolp** [comment]
@MEy3 I created a pull request with your changes.

Sadly I was not able to test this, as I wasn't able to run current master against our oVirt 4.3 installation.

**Comment by wefixit-AT** [comment]
I created a new branch to test against my oVirt 4.3 environment. There I changed the line. I'm not sure if double "_" solves the problem. Please test the branch with your version.

**Comment by stolp** [comment]
I will test this, thanks!

**Comment by MEy3** [comment]
The „__“ is the separator between VMname and Date. Without “__” the script fails to get the proper name of the Test1 vm snapshot and deletes the last one that can be found from Test2 which is wrong. Also it happend that not only the wrong snapshot get’s deleted also so entire VM Test2 incl. Discimage image. That happens twice so I had to restore it from an older backup and modified the script last year. “__*” takes care to get the exact name of the vm and ensure due to the separator to only delete the correct snapshot.

**Comment by wefixit-AT** [comment]
It is not possible with any release that the whole VM is delete only if you have nothing set to "vm_middle" in your config. But if you wish I add this to the master and oVirt4.3 branch

**Comment by wefixit-AT** [comment]
If you still unsatisfied, leave a comment.
