### ISSUE TITLE
Imported VM deleted in backup rotation

### ISSUE THREAD

**Issue by imperativa28** [wefixit-AT/oVirtBackup#62]
![image](https://user-images.githubusercontent.com/48401306/100303947-473fd200-2fd0-11eb-909d-9d257a3820d0.png)

**Tarsus** is the name of VM imported from backup created by this script.

If the VM is imported in the same cluster (for instance when there's a misconfiguration so they had to be restored from the backup in the same cluster) the VM is deleted in the rotation process. Is this intentional or there are any configuration I should use to only delete the rotated backup (prefixed with date) but not the imported-from-backup-vm ?

I tried to change the name, collapse snapshot and/or clone but it still gets deleted. Any help will be appreciated.
Thank you!

**Comment by imperativa28** [comment]
My apologies, the VM is deleted because i use similar prefix for the imported VM (Tars and Tarsus). It doesn't happen when I use different name for the imported VM

**Comment by stolp** [comment]
I think this is issue #60 you are experiencing here.
