### ISSUE TITLE
Export VM directly from a snapshot

### ISSUE THREAD

**Issue by wefixit-AT** [wefixit-AT/oVirtBackup#7]
With the current oVirt SDK its only possible to export a VM to the backup storage, there the following workflow is needed.

Create snapshot -> Clone into VM -> Delete Snapshot -> Export cloned VM -> Delete cloned VM
Disadvantage: The storage of the VM is needed because it has to be cloned to export it.

If the SDK support direct export from a snapshot this will give a huge performance impact.

State: Request sent to oVirt

**Comment by paf1** [comment]
wait for oVirt community response  .....

**Comment by GusevVictor** [comment]
Dear all, can you explain to me about workflow one more time please?

So, I have 500 gb local_storage. I have a vm wich is 300 gb. I have connected export NFS domain storage.

Can I do a backup or not in this case?

If see the workflow it will be like this: Create snapshot from my 300 gb vm -> Clone into VM ????? - Will it fail because I need as least 300 gb free space in my local_storage? Thank for you responce to me.

**Comment by wefixit-AT** [comment]
Yes sadly you are true. In this case it is not possible because you need 100gb more free space + a little bit more because it can be that you can't delete the snapshot. During that huge backup a lot of changes will increase the snapshot file.

Maybe it is possible to move the data from the VM to the host and share the files to the VM via NFS or Samba to the VM.

For example:
VM: Disksize: 300GB -> 50GB operating system + 250GB Data
Move the 250GB Data to the host and share it to the VM. Then you have 50GB for the VM which can be backed up with your free space of 200GB on the storage

**Comment by GusevVictor** [comment]
Big thank for you answer to me. I was wondering if you answer to the next question:

Is it possible to add second data storage in a local_DC, and clone a vm to the new storage? It can be like this one in config.conf: like clone_domain_storage=. If possbile.

Best regards,
Victor.

**Comment by dyasny** [comment]
What you can do instead of using an export domain, is create an NFS data domain instead, and clone VMs from the snapshot directly onto it. oVirt 3.5+ allows importing/connecting data domains from other DCs if you need mobility, and the RTO will be lower because these backups can be started right away from NFS instead of going through a long import first

**Comment by wefixit-AT** [comment]
@dyasny: Thats a good idea. I will test it when I have some spare time to work on my open source projects.

**Comment by paf1** [comment]
Hi,
keep both possibilities of backup domain  ( NFS-export & NFS-data ) , pls.
thx.regs.Pa.

**Comment by wefixit-AT** [comment]
@dyasny: Where should this option be? I have oVirt 3.6 with the latest updates but I see no option to export a snapshot to a NFS data domain or any option to selection another export destination

**Comment by dyasny** [comment]
When you clone a VM from snapshot, you can choose where the VM's disks will be placed. It's not export as such, it's just a cloning of a VM with the destination storage domain selected as the NFS domain where you store backups.

**Comment by wefixit-AT** [comment]
Ah, I forget to add a disk to my test VM ;-)
The only problem we get here is that the VM is displayed in the VM list.
Do you have an idea how to remove it from the list?

Now it looks we can use the temporary NFS as buffer for the main storage domain. After cloning the VM can be exported to the export domain and then removed from the temporary NFS share. Then the VM list will be clean again.

**Comment by dyasny** [comment]
> The only problem we get here is that the VM is displayed in the VM list.

Well, that's normal. I'd tag it as a backup, with date-time maybe. 

>Now it looks we can use the temporary NFS as buffer for the main storage domain. After cloning the 
>VM can be exported to the export domain and then removed from the temporary NFS share. Then 
>the VM list will be clean again.

You can even implement a nice staging/backup scheme this way - use the data SD as a staging location, and maybe rsync VM disks from there to a deduplicated storage. There you can utilize stuff like rsync or virt-diff to start playing with actual differential and incremental backups, libguestfs for file-level restores

> Update: How is the idea to make a template of the VM?

I don't see much of a use for that, templates are, after all, intended to be stateless blobs for real machines to derive from, and backups are the very definition of statefulness
