### ISSUE TITLE
Move suffix from timestamp to readable format

### ISSUE THREAD

**Issue by wefixit-AT** [wefixit-AT/oVirtBackup#8]
as asked in issue #6  from paf1:

> Well , this is fixed now, but would you generate human number format suffix ( 1501212245 eg:? ), pls.,
> regs. Pavel

**Comment by paf1** [comment]
Hello, 
fixed, runing OK, with no problems .
Still one note, would you delete seconds from string ? Not needed.
regs.
Pavel
