### ISSUE TITLE
can't delete temporary snapshot  called "Snapshot for backup script"

### ISSUE THREAD

**Issue by paf1** [wefixit-AT/oVirtBackup#9]
Hello,
if a new snapshot and clone created to filled up storage, then is not possible delete that snapshot due to " not enought space to delete snapshot"  and "snapshot delete" requests stay permanently in cycle.
Therefore , would you change sequence of backup steps to  snapshot -> clone -> move clone -> delete orig.clone -> delete snapshot ?
OR
check status of "delete snapshot" step and move this to end of backup steps if such error occured 

regs.
Pavel

**Comment by wefixit-AT** [comment]
That's a good point, it never occurs on my host that the storage are filled up.
I think it would be better to check before the backup of a individual VM is started if there is enough free space + safety coefficient. If there are to less storage the backup would be skipped for safety reason.
Hopefully its possible to get the needed information with the SDK.

In detail:

1. Get VM size (vm_size)
2. Get storage free size (storage_free_space)
3. if vm_size*1.1>storage_free_space -> skip

The safety coefficient will be changeable in the config (0-100%

**Comment by paf1** [comment]
one additional note:
If clone is migrated, would you enable/disable  snapshot consolidation in config file ? For each VM separately.
thx.Pa.

**Comment by wefixit-AT** [comment]
Update: I start working on this. The first part will be the space problem, can you create for the other request a separate entry.

**Comment by wefixit-AT** [comment]
Thanks for reporting this. Can you please checkout the latest version and give a short feedback if I can close this request.

**Comment by paf1** [comment]
Hi,
  will test this week .
!! You forgot update tar ball !! .
Pa.

**Comment by wefixit-AT** [comment]
what?

**Comment by paf1** [comment]
Hello,
just checked  config file and I found error .

You can't define VM storage explicitly in "storage_domain" variable in 
config file because storage  is  changing in gluster  from one to 
another as we need ( manually - "disk move" operation  ) = storage name 
is NOT fix .
This value has to be taken from VM record from oVirt database to get the 
right value .
Pa.

**Comment by wefixit-AT** [comment]
Ok, I will fix this next week or the week after.

**Comment by paf1** [comment]
direct email sended to you with picture

**Comment by wefixit-AT** [comment]
Normally this is automatically done by github after a new commit was made.

Has anybody other information's to this issue?
